name: CorNetMeSHProbeNet

model:
  hidden_size: 300
  n_layers: 2
  n_probes: 5
  dropout: 0.5

train:
  batch_size: 200
  nb_epoch: 10
  swa_warmup: 2

valid:
  batch_size: 200

predict:
  batch_size: 200
#/p/realai/sneha/cornet2/CorNet/data/Mesh-2022
path: /p/realai/sneha/cornet2/CorNet/data/Mesh-2022/models
