name: CorNetXMLCNN

model:
  dynamic_pool_length: 8
  bottleneck_dim: 512
  num_filters: 128
  dropout: 0.5
  emb_trainable: False

train:
  batch_size: 40
  nb_epoch: 30
  swa_warmup: 10

valid:
  batch_size: 40

predict:
  batch_size: 40

path: /p/realai/guangxu/2020xmtc/deep_data/EUR-Lex/models
