name: MeSHProbeNet

model:
  hidden_size: 300
  n_layers: 2
  n_probes: 5
  dropout: 0.5

train:
  batch_size: 200
  nb_epoch: 10
  swa_warmup: 2

valid:
  batch_size: 200

predict:
  batch_size: 200

path: /p/realai/guangxu/2020xmtc/deep_data/AmazonCat-13K/models
